{{- if .Values.hermes.api.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-api
  minReplicas: {{ .Values.hermes.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hermes.api.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hermes.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
