{{- $dbSec := default (dict "secretName" "" "value" "") .Values.bugsink.secrets.DATABASE_URL -}}
{{- if or (and (not $dbSec.secretName) (not $dbSec.value)) .Values.bugsink.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ .Chart.Name }}-mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app: {{ .Chart.Name }}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-mariadb
    spec:
      {{- if .Values.bugsink.mariadb.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.bugsink.mariadb.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}  
      containers:
        - name: mariadb
          image: {{ .Values.bugsink.mariadb.image }}
          env:
            - name: MARIADB_ROOT_PASSWORD 
              value: rootpass
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-db" .Release.Name }}
                  key: db-name
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-db" .Release.Name }}
                  key: db-username
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-db" .Release.Name }}
                  key: db-password
          ports:
            - containerPort: 3306
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 2
            periodSeconds: 2
          resources:
{{- toYaml .Values.bugsink.mariadb.resources | nindent 12 }}
{{- end }}
