{{- if .Values.flyanData.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "flyan-data.labels" . | nindent 4 }}
  {{- with .Values.flyanData.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.flyanData.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.flyanData.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.flyanData.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-api
                port:
                  number: 80
          {{- end }}
    {{- end }}
{{- end }}
